### PR TITLE
Remove plugin comment line

### PR DESCRIPTION
**Pull request by llfrometa89**
I think this line is not necessary

### CODE REVIEW

**Comment by rossabaker** [comment]
We had that in there as a suggestion, but we should:
1. Take it out, like this PR
2. Comment why we strongly suggest it's on
3. Turn it on for people

I use it on every new project, and it's easiest when you start new, but the concern was that some of the strict flags it enables would intimidate people new to Scala.  I'm leaning toward starting people off on the right foot, though.

Discuss.

**Comment by llfrometa89** [comment]
Ok, I thought that was a mistake. I'm ok with that.

**Comment by ChristopherDavenport** [comment]
My only concern with turning it on for people is that we are doing more than the minimal, that being said we are now actively helping design with algebras in this base template, so perhaps adding the flags we think are most apt are appropriate, we could always introduce a comment over the plugin stating this as well.

**Comment by rossabaker** [comment]
We failed to follow up on this, but it's the right thing absent those other actions.  Might as well merge it instead of close it.

Starting in 0.21, we left the plugin on.

**Pull request merged**
