### PR TITLE
Kind projector commented

### PR DESCRIPTION
**Pull request by ChristopherDavenport**

### CODE REVIEW

**Review by rossabaker — COMMENTED** [review]
I see no harm in enabling this one by default.  Unlike tpolecat, it doesn't make anything harder.  In fact, it makes copy and pasting from Typelevelly stuff more likely to work.

**Comment by jmcardon** [comment]
:+1: on default enable.

**Review by jmcardon — APPROVED** [review]

**Comment by aeons** [comment]
Does this work? Putting it in plugins.sbt?

**Comment by ChristopherDavenport** [comment]
Oh my!

**Comment by jmcardon** [comment]
LOL.... I didn't catch that either

**Pull request merged**
