### PR TITLE
Abstract IO and define it in a single location

### PR DESCRIPTION
**Pull request by jcranky**
I change this every time I create a new http4s app :)

### CODE REVIEW

**Review by ChristopherDavenport — COMMENTED** [review]
If I were to make this closer to default I would do everything explicitly rather than utilizing inheritance except for the main which just calls a function.

This is an improvement over what is here, so I can make those improvements, or we can work through what they would look like here.

**Comment by jcranky** [comment]
@ChristopherDavenport  Lets do it here if you don't mind, although I don't fully understand what you would change.

**Comment by ChristopherDavenport** [comment]
Firstly as a new service definition
```scala
def service[F[_]]: HttpService[F] = {
  val dsl = new Http4sDsl[F]{}
  import dsl._
  HttpService[F] {
     case GET -> Root / "hello" / name =>
       Ok(Json.obj("message" -> Json.fromString(s"Hello, \${name}")))
   }
}
```
Secondly, the stream should also be abstracted from the call site. As our whole app is a Stream, it can be described as a value derived from an abstract parameter F[_]: Effect and implicite ExecutionContext.

**Comment by jcranky** [comment]
@ChristopherDavenport I did the service part, and moved it to its own file. Will have a look at the stream part later :)

**Comment by jcranky** [comment]
@ChristopherDavenport I gave it a go on the stream part, what do you think?

**Comment by rossabaker** [comment]
Wow, I never do the DSL that way.  If I were to do it that way, I'd do it outside the service definition, so it doesn't get copied and pasted if the class has multiple services.  And doing it outside the service definition... makes it something that can be mixed in via a trait.

Is there a specific objection?  I know OO is scary, but this is a case that doesn't really bother me.

**Comment by jmcardon** [comment]
+1. I usually put the services in a class, to abstract out the `F`. Often enough that class also serves for me as a place to inject dependencies vs implicits or something.

I'm not pro `new Http4sDsl[F]` just for importing it.

**Comment by aeons** [comment]
IME there are these [three styles](https://gist.github.com/aeons/376f64913658f3ab2f6a0b94712ba156). 

I’ve always used the inheritance approach, but I think Chris prefers one of the more functional versions. 

I also think the inheritance version is easier to understand for newcomers, so maybe use that in the template?

**Comment by jcranky** [comment]
My preference is also towards inheritance in this case. My services tend to be classes anyway, because I pass them some constructor parameters. I also am starting to prefer to constrain `F` to `Effect` right away. PR Updated, what do you think?

**Comment by SystemFw** [comment]
There isn't really any difference between `extends Dsl[F]` and `new Dsl[F]`. They are both technically using inheritance, and neither is doing it for anything more than scoping and instantiation. 
So I don't see any argument against `extends Dsl[F]` on "functional grounds".

If it makes your conscience cleaner, you can think of that as instantiating an ML Functor at type `F`.

**Comment by jcranky** [comment]
No one cares about this one? :D

**Review by ChristopherDavenport — APPROVED** [review]
My style was beaten into submission. I will continue to write that way. I think this seems fine.

**Comment by jcranky** [comment]
Anyone against merging this ? XD

**Pull request merged**
