### PR TITLE
Add CC 1.0 License

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
Should probably have all committers sign so all work is without question public domain. 

I obviously am not the sole author, which makes the legitimacy without other signatories rather weak.

### CODE REVIEW

**Comment by rossabaker** [comment]
I approve.

We could tag the other contributors and hope that all comment.  (I'm surprised that there are nine already!)  Should also add a CONTRIBUTING.md to make clear that future PRs are covered by this.

**Comment by ChristopherDavenport** [comment]
I'll add that, and incorporate you into the PR.

Reaching out to other contributors for approval as well.

cc @LukaJCB @bneil @NicolasRouquette @xuwei-k @j-keck @evilantnie

**Review by LukaJCB — APPROVED** [review]
100% Approved! :)

**Review by xuwei-k — APPROVED** [review]

**Comment by rossabaker** [comment]
I think we're going to need a timeout on this.  I can't imagine anybody objects to this, but I'd also be surprised if we hear back from everyone.

**Comment by ChristopherDavenport** [comment]
I say we merge and can complete at the end of the month.

**Pull request merged**
