### PR TITLE
Add partial unification

### PR DESCRIPTION
**Pull request by kubukoz**
Probably only makes sense on 2.11.9+ and 2.12.x, so feel free to close if we don't want to cause broken builds for users of older Scala versions :)

(not that anyone would willingly create a new project with an ancient Scala veresion)

### CODE REVIEW

**Review by jmcardon — APPROVED** [review]

**Comment by ChristopherDavenport** [comment]
I believe we already have this via plugin. https://github.com/http4s/http4s.g8/blob/0.18/src/main/g8/project/plugins.sbt

**Comment by kubukoz** [comment]
Ohh cool, I didn't notice. Do you think we should still support these older
versions?

**Comment by rossabaker** [comment]
I guess it's not strictly necessary anymore since we dropped 2.10, and as a template project, nobody should be starting, say, 2.11.7.  I think we should have one or the other.

**Comment by rossabaker** [comment]
So we can remove the plugin or close this PR.  I guess the plugin is heavier than the one-liner, so we should probably keep this and lose the plugin.

**Comment by aeons** [comment]
That sounds good. @kubukoz, would you remove the plugin as part of this PR?

**Comment by kubukoz** [comment]
Yeah, it's on my to-do list :)

**Comment by kubukoz** [comment]
Sorry for the massive delay. Finally removed the plugin.

**Review by rossabaker — APPROVED** [review]

**Pull request merged**
