### PR TITLE
Add sample application with plain IO

### PR DESCRIPTION
**Pull request by AL333Z**
Hi,
This is a follow-up of a conversation ended here https://discord.com/channels/632277896739946517/632286375311573032/897512259931238440

In short, having another sample that sticks `IO` as the effect type may be helpful for newcomers.
Hope you find this useful :)

### CODE REVIEW

**Comment by rossabaker** [comment]
Thanks. I appreciate the effort, but I need convincing:

1. We may be sparing users from learning to _write_ tagless final, but they still have to _read_ it in the libraries they build on, including http4s and fs2.  Is having two styles really easier than making one style read-write?

2. Is it clear to a novice user that they only need one half of this?  The readme says so, but new users plow ahead without reading the readme.

Newcomers benefit from something prescriptive: one style, no decisions until they get comfortable.  My leaning is that this would be better in a branch or in an alternate g8 template for people who prefer the style, and we can reference it as an alternate style, but try not to muddle the message of introductory docs.

**Comment by AL333Z** [comment]
Yeah, I get your points, and I really don't have proper counterarguments :)

> Newcomers benefit from something prescriptive: one style, no decisions until they get comfortable. 

As an ex-newcomer myself, I really agree with this.

My subjective view on this is that sticking to `IO` will let the first-time application developer have a thing less to know before being up-to-speed (even if, as you say, it still needs to know somehow what is TF due to the libs it's using). But again, that's just my personal view on the topic and discussions like the one in that thread seem to be aligned with my feeling.

> My leaning is that this would be better in a branch or in an alternate g8 template for people who prefer the style

This sounds like a great idea! Which one do you prefer? A branch here or a brand new repo (under the http4s org maybe?)

**Comment by AL333Z** [comment]
Either way, I think this PR should be closed.
I just force-pushed to remove the package distinction, so if you chose to put it in a branch/new repo you'll have all you need already in place :)

**Comment by rossabaker** [comment]
Sorry, lost track of this one.  I'll spin up a new repo with this.  Thanks for adding it!

**Comment by rossabaker** [comment]
Okay, it's live at https://github.com/http4s/http4s-io.g8.

**Pull request closed without merging**
