### PR TITLE
Use https typesafe resolver to suppress warnings

### PR DESCRIPTION
**Pull request by aaabramov**

### CODE REVIEW

**Comment by aaabramov** [comment]
I am not sure why builds started to fail on all PRs. Could someone clarify that to me please?

**Comment by rossabaker** [comment]
Looks like a GraalVM error.  I don't understand why it would only be triggering on PRs.

This change looks good, but I wonder: do we even need this resolver at all?

**Comment by rossabaker** [comment]
Looks similar to https://users.scala-lang.org/t/graalvm-compilation-to-native-image-fails-scala-2-13-1/5263/2?

**Comment by rossabaker** [comment]
The graalvm build appears to be broken for other reasons, so let's not block this.

**Pull request merged**
